server:
  port: 9040
spring:
  profiles:
    active: dev

---
spring:
  profiles: dev
  data:
    mongodb:
      host: localhost
      port: 27017
      database: hourglass
  cloud.stream:
    bindings:
      input-users:
        destination: users
        group: favouritegroup
      input-movies:
        destination: movies


---
spring:
  profile: prod
  data:
    mongodb:
      host: localhost
      port: 27018
      database: hourglass
  cloud.stream:
    bindings:
      input-users:
        destination: users
      input-movies:
        destination: movies
