server:
  port: 9040
spring:
  profiles:
    active: dev
  cloud.stream:
    bindings:
      input-users:
        destination: users
        group: favouritegroup
      input-movies:
        destination: movies
---
spring:
  profiles: dev
  data:
    mongodb:
      host: localhost
      port: 27017
      database: hourglass



---
spring:
  profile: prod
  data:
    mongodb:
      host: mongodb
      port: 27017
      database: hourglass

