server:
  port: 9040
spring:
  profiles:
    active: dev
  cloud.stream:
    bindings:
      input-users:
        destination: users
        group: favouritegroup
      input-movies:
        destination: movies
    defaultBinder: rabbit
    default.contentType: application/json


---
spring:
  profiles: dev
  data:
    mongodb:
      host: localhost
      port: 27017
      database: hourglass

spring.rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest




---
spring:
  profile: prod
  data:
    mongodb:
      host: hourglassdb-service
      port: 27017
      database: hourglass

spring.rabbitmq:
  host: rabbitmq
  port: 5672
  username: guest
  password: guest

